spring.datasource.url: jdbc:postgresql://localhost:5432/appliance?allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
spring.datasource.username: postgres
spring.datasource.password: root
spring.jpa.hibernate.ddl-auto: none
spring.datasource.hikari.maxLifeTime: 60000

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db.changelog\changelog-master.xml
spring.jackson.serialization-inclusion: non_null
